In [5]:
import tensorflow as tf
import functions as funcs 
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = funcs.gen_cnn_series(10, 9)

In [3]:
data

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 16],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 17],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 18],
 [3, 4, 5, 6, 7, 8, 9, 10, 11, 19],
 [4, 5, 6, 7, 8, 9, 10, 11, 12, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 21],
 [6, 7, 8, 9, 10, 11, 12, 13, 14, 22],
 [7, 8, 9, 10, 11, 12, 13, 14, 15, 23],
 [8, 9, 10, 11, 12, 13, 14, 15, 16, 24],
 [9, 10, 11, 12, 13, 14, 15, 16, 17, 25]]

In [46]:
def gen_np_cnn_series(examples, lenght, reverse=False):

    series = np.random.rand(examples, lenght)
    if not reverse:
        for el in range(0, examples):
            add = np.random.choice([10,11])
            progression = np.arange(start=el, stop=el + lenght - 1, step=1)
            series[el, :-1] = series[el, :-1] + progression 
            series[el, -1] = 1
        return series[:, :-1], series[:, -1], series.shape
    else:    
        for el in range(0, examples):
            add = np.random.choice([10,11])
            progression = np.arange(start=el + lenght - 1, stop=el, step=1)
            series[el, :-1] = series[el, :-1] + progression 
            series[el, -1] = 1
        return series[:, :-1], series[:, -1], series.shape

x_train, y_train, shape = gen_np_cnn_series(3, 4)
x_train, y_train, shape = gen_np_cnn_series(3, 4, reverse=True)


print(x_train, y_train)

[[0.10845013 1.31699277 2.44528376]
 [1.56478839 2.95844069 3.14472775]
 [2.94736173 3.0538879  4.58659443]] [1. 1. 1.]
